services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: delta_database
      MYSQL_USER: delta-service-account
      MYSQL_PASSWORD: password

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
