name: Tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build container images for app and MySQL
        run: docker compose build
      - name: Start containers
        run: docker compose up -d
      - name: Run tests
        run: docker compose exec app mvn test
      - name: Shut down containers
        if: always()
        run: docker compose down -v
